### PR TITLE
Version bump - 3.10.0

### PR DESCRIPTION
**Pull request by Justintime50**
Bumping version to 3.10.0 for all the changes that happened two weeks ago.

### CODE REVIEW

**Comment by Justintime50** [comment]
@Roguelazer how would you like to handle this PR? We had a bunch of changes merged to master some months ago that never had a new version cut.

**Comment by Roguelazer** [comment]
I'll merge it after I get the broken build figured out. If it turns out that I need to drop node 6 support then we'll need to redo this as a major version bump.

**Comment by Roguelazer** [comment]
Okay, want to rebase this on master?

Note that you have to rerun the `npm run build` to generate the checked-in compiled products, too.

**Review by Roguelazer — APPROVED** [review]
seems ok

**Pull request merged**
