### PR TITLE
use new post endpoint for regenerateRates

### PR DESCRIPTION
**Pull request by Roguelazer**
The GET method is being made read-only in the future.

### CODE REVIEW

**Review by jontsai — DISMISSED** [review]
LGTM

**Comment by Justintime50** [comment]
@Roguelazer could we get a rebase here? If tests pass we can get this merged in.

**Comment by Justintime50** [comment]
I fixed the merge conflicts here but tests are failing because the function name changed. We'll need to have the tests adjusted @Roguelazer

**Review by Justintime50 — DISMISSED** [review]
I pushed up a fix for the tests, build passes now.

**Review by Sarahbear1926 — APPROVED** [review]

**Review by ejachang — DISMISSED** [review]

**Review by jontsai — DISMISSED** [review]

**Review by Sarahbear1926 — APPROVED** [review]

**Pull request merged**
