### PR TITLE
Fixes polly in ep tests

### PR DESCRIPTION
**Pull request by ralexmatthews**
# Description

There was an alert that there was an auth header in some of the cassettes in the easypost request hooks tests. I believe this is because we weren't using polly correctly in those tests. 

This PR basically just changes how we init polly and the EP client to be more consistent with the other tests, and then re-records the cassettes.

# Testing

This is only testing changes, so I ran the tests and they passed

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

### CODE REVIEW

**Comment by nwithan8** [comment]
Code looks good and unit tests passed, if you can address the CVE in the linting step.

**Comment by ralexmatthews** [comment]
How can I address the CVE?

**Comment by Justintime50** [comment]
@ralexmatthews either by bumping the bad dependency or adding it to the ignore list

**Comment by ralexmatthews** [comment]
Ah I see. I thought you were referring to the security thing you sent me that prompted this change lol pushed changes 👍

**Review by nwithan8 — APPROVED** [review]

**Pull request merged**
